version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly