version: '3.9'

services:
  amq:
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    hostname: amq
    ports:
      - 61613:61613
      - 8161:8161

  novelworkernode:
    image: novelworkernode
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - amq
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: [ "node", "--inspect=0.0.0.0:9229", "src/index.js" ]
