version: "3.8"

services:
  # Start localstack per docker compose to have it in a separate network with a consistent hostname.
  # The hostname can then be referenced in the application configuration.
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    hostname: "localstack"
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=0
      # - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMP}/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
