name: ci

on:
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: docker compose -f docker-compose.ci.yml up -d
      - name: Wait for Localstack to be running
        run: |
          until [ "$(curl --insecure -s "localhost:4566" | jq '.status == "running"')" ]; do
            sleep 10
            docker ps -a
            curl --insecure -v "127.0.0.1:4566"
            curl --insecure -v -s "127.0.0.1:4566" | jq '.status == "running"'
          done
      - run: chmod 500 create-localstack-resources.sh && ./create-localstack-resources.sh

      - run: npm ci
      - run: npm run integration-test

      - name: extract logs
        if: ${{ failure() }}
        run: docker compose logs > docker-compose.log
      - name: upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: docker-compose.logs
