name: release

env:
  IMAGE_NAME: xiangronglin/novel-worker-node

on:
  push:
    branches:
      # - master
    paths-ignore:
      - "README.md"
      - ".devcontainer"
      - ".vscode"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:latest -t ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Docker Hub push
        # run: docker push ${{ env.IMAGE_NAME }} -a

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: ECR login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com

      - name: ECR push
        run: docker push ${{ env.IMAGE_NAME }} -a
