name: release

env:
  IMAGE_NAME: xiangronglin/novel-worker-node
  ECR_REGISTRY: public.ecr.aws

on:
  push:
    branches:
    # - master
    paths-ignore:
      - "README.md"
      - ".devcontainer"
      - ".vscode"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build . \
          -t ${{ env.IMAGE_NAME }}:latest \
          -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          -t ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Docker Hub push
      # run: docker push ${{ env.IMAGE_NAME }} -a
      - name: public ECR login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}
          ecr: true
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_ACCESS_KEY }}
        # env:
        # AWS_REGION: eu-central-1

      - name: Docker Hub and ECR push
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }} -a
