name: release

env:
  IMAGE_NAME: novel-worker-node
#  ECR_REGISTRY: public.ecr.aws
#  ECR_ALIAS: c2s9m0s3

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".vscode"

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  build-and-release:
    # needs:
      # - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

#      - name: public ECR login
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ env.ECR_REGISTRY }}
#          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
#          password: ${{ secrets.ECR_ACCESS_KEY }}
#
#      - name: public ECR push
#        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_ALIAS }}/${{ env.IMAGE_NAME }} -a
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-release
  #   steps:
  #     - name: Trigger deploy
  #       run: |
  #         curl -X POST -H "X-Hub-Signature: sha1=${{ secrets.WEBHOOK_SHA_1 }}" http://${{ secrets.VM_URL }}:9000/hooks/redeploy
            
