name: release

env:
  IMAGE_NAME: novel-worker-node
#  ECR_REGISTRY: public.ecr.aws
#  ECR_ALIAS: c2s9m0s3

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".devcontainer"
      - ".vscode"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build . \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
#          -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_ALIAS }}/${{ env.IMAGE_NAME }}:latest \
#          -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_ALIAS }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }} -a

#      - name: public ECR login
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ env.ECR_REGISTRY }}
#          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
#          password: ${{ secrets.ECR_ACCESS_KEY }}
#
#      - name: public ECR push
#        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_ALIAS }}/${{ env.IMAGE_NAME }} -a
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Trigger deploy
        run: |
          curl -X POST -H "X-Hub-Signature: sha1=${{ secrets.WEBHOOK_SHA_1 }}" http://${{ secrets.VM_URL }}:9000/hooks/redeploy
            
